version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn camila_sanfuentes_com.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/camila_sanfuentes_com/web/static
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/camila_sanfuentes_com/web/static
    ports:
      - 80:80
      - 443:443

    depends_on:
      - web
volumes:
  static_volume:
  postgres_data:
