# Generated by Django 3.2.5 on 2023-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camila_sanfuentes_com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='portrait',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='main_page'),
        ),
    ]
