# Generated by Django 3.2.5 on 2021-10-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20211018_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_top_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
