# Generated by Django 3.2.5 on 2023-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_gallery_top_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='carousel_image',
            field=models.BooleanField(default=False),
        ),
    ]
