# Generated by Django 3.2.8 on 2021-10-11 00:43

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=150)),
                ('post_header_image', models.ImageField(null=True, upload_to='blog_images')),
                ('post_image', models.ImageField(null=True, upload_to='blog_images')),
            ],
        ),
    ]
