# Generated by Django 3.2.8 on 2021-10-12 01:04

from django.db import migrations
import editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
    ]
